### PR TITLE
added the navigation section

### PR DESCRIPTION
**Pull request by jomefavourite**
Signed-off-by: jomefavourite <jfjomefavourite@gmail.com>

### CODE REVIEW

**Comment by jomefavourite** [comment]
Here's a preview

**Comment by dhanielcodes** [comment]
-The nav has some space around it
-Border radius wasn't added
-No desktop view preview screenshot
-The nav should be fixed to the bottom

**Comment by jomefavourite** [comment]
Fixed the nav for both mobile and desktop views
scrnli_2_25_2021_2-27-57 PM
scrnli_2_25_2021_2-28-17 PM

Contents need to be added before it'll be vertical

**Comment by dhanielcodes** [comment]
The desktop nav is not meant to be on the bottom, check the design

**Comment by jomefavourite** [comment]
> The desktop nav is not meant to be on the bottom, check the design

I know, there aren't contents that why I left it like that. I feel it pointless moving it to the right now but if that's what you want I can do that.

**Comment by jomefavourite** [comment]
> The desktop nav is not meant to be on the bottom, check the design

I know, there aren't contents that why I left it like that. I feel it pointless moving it to the right now but if that's what you want I can do that.

**Comment by dhanielcodes** [comment]
Also, make the nav icons have an active state on click, instead of hardcoding them

**Comment by dhanielcodes** [comment]
> > The desktop nav is not meant to be on the bottom, check the design
> 
> I know, there aren't contents that why I left it like that. I feel it pointless moving it to the right now but if that's what you want I can do that.

Yes do that, follow the design, it's crucial

**Comment by jomefavourite** [comment]
> Also, make the nav icons have an active state on click, instead of hardcoding them

Ok

**Comment by jomefavourite** [comment]
Added mobile, tablet and desktop view

scrnli_2_25_2021_5-59-47 PM
scrnli_2_25_2021_5-59-24 PM
scrnli_2_25_2021_5-59-09 PM

**Pull request merged**
